# Generated by Django 3.0.8 on 2020-07-23 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("resources", "0002_tag_website")]

    operations = [
        migrations.DeleteModel(name="Website"),
        migrations.AddField(
            model_name="tag",
            name="resource",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resources.Resource",
            ),
        ),
    ]
